*&---------------------------------------------------------------------*
*& Include          ZDSUWON02_TEST_01_TOP
*&---------------------------------------------------------------------*
TABLES : ZTSUWON02_HR.

DATA : BEGIN OF GS_DATA,
        ZCODE TYPE ZTSUWON02_HR-ZCODE,
        ZNAME TYPE ZTSUWON02_HR-ZNAME,
        CHECK,
        INT TYPE I,
        INFO(4),
        CTAB TYPE LVC_T_SCOL,
        STYLE TYPE LVC_T_STYL,
       END OF GS_DATA,
       GT_DATA LIKE TABLE OF GS_DATA.

DATA : GS_FCAT TYPE LVC_S_FCAT.
DATA : GT_FCAT TYPE LVC_T_FCAT.
DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GS_LAYOUT2 TYPE SLIS_LAYOUT_ALV.
DATA : GS_FCAT2 TYPE SLIS_FIELDCAT_ALV,
       GT_FCAT2 TYPE SLIS_T_FIELDCAT_ALV.

DATA : GS_SCOL TYPE LVC_S_SCOL.
DATA : GS_STYLE TYPE LVC_S_STYL.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.
DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
DATA : GC_CONTAINER_1 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER_2 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_GRID_1 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID_2 TYPE REF TO CL_GUI_ALV_GRID.

DATA : LV_TABIX TYPE SY-TABIX.

DATA : GS_SORT TYPE LVC_S_SORT,
       GT_SORT TYPE LVC_T_SORT.
DATA : GS_VARIANT TYPE DISVARIANT.
DATA : GT_TOOLBAR TYPE UI_FUNCTIONS.
