*&---------------------------------------------------------------------*
*& Report ZDSUWON02_1014
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDSUWON02_1014.

DATA : BEGIN OF GS_DATA,
        ZDEPT TYPE ZDSUWONT02-ZDEPT,
        ZDNAME TYPE ZDSUWONT02_3-ZDNAME,
        ZEMPNO TYPE ZDSUWONT02-ZEMPNO,
        ZEMPNM TYPE ZDSUWONT02-ZEMPNM,
        ZGENDER(4),
        ZSDATE TYPE ZDSUWONT02-ZSDATE,
       END OF GS_DATA,
       GT_DATA LIKE TABLE OF GS_DATA.

DATA : BEGIN OF GS_DEPT,
        ZDEPT TYPE ZDSUWONT02_3-ZDNAME,
        ZDNAME TYPE ZDSUWONT02_3-ZDNAME,
       END OF GS_DEPT,
       GT_DEPT LIKE TABLE OF GS_DEPT.

DATA : GS_MAIN LIKE GS_DATA,
       GT_MAIN LIKE TABLE OF GS_DATA.

SELECT ZDEPT ZEMPNO ZEMPNM ZGENDER ZSDATE
  INTO CORRESPONDING FIELDS OF TABLE GT_DATA
  FROM ZDSUWONT02.

SELECT ZDEPT ZDNAME
  INTO CORRESPONDING FIELDS OF TABLE GT_DEPT
  FROM ZDSUWONT02_3.

LOOP AT GT_DATA INTO GS_DATA.
  CLEAR GS_DEPT.
  READ TABLE GT_DEPT WITH KEY ZDEPT = GS_DATA-ZDEPT INTO GS_DEPT.
  IF SY-SUBRC = 0.
    GS_DATA-ZDNAME = GS_DEPT-ZDNAME.
    MODIFY GT_DATA FROM GS_DATA.
    CLEAR GS_DATA.
  ENDIF.
ENDLOOP.

LOOP AT GT_DATA INTO GS_DATA.
  CONDENSE GS_DATA-ZGENDER.
  IF GS_DATA-ZGENDER = '여'.
    GS_DATA-ZGENDER = '여자'.
  ELSE.
    GS_DATA-ZGENDER = '남자'.
  ENDIF.
  MODIFY GT_DATA FROM GS_DATA.
  CLEAR GS_DATA.
ENDLOOP.

SORT GT_DATA.
LOOP AT GT_DATA INTO GS_DATA.

  WRITE : / GS_DATA-ZDEPT,
            GS_DATA-ZDNAME,
            GS_DATA-ZEMPNO,
            GS_DATA-ZEMPNM,
            GS_DATA-ZGENDER,
            GS_DATA-ZSDATE.

  AT END OF ZDEPT.
    WRITE : SY-ULINE.
  ENDAT.
ENDLOOP.

"부서별 부양가족수 합계치
"부서코드(10개)/부서명/부양가족수
DATA : BEGIN OF GS_DATA2,
        ZDEPT TYPE ZDSUWONT02-ZDEPT,
        ZDNAME TYPE ZDSUWONT02_3-ZDNAME,
        ZFAMNO TYPE ZDSUWONT02-ZFAMNO,
       END OF GS_DATA2,
       GT_DATA2 LIKE TABLE OF GS_DATA2.

DATA : BEGIN OF GS_DEPT2,
        ZDEPT TYPE ZDSUWONT02_3-ZDEPT,
        ZDNAME TYPE ZDSUWONT02_3-ZDNAME,
       END OF GS_DEPT2,
       GT_DEPT2 LIKE TABLE OF GS_DEPT2.

DATA : GS_MAIN2 LIKE GS_DATA2,
       GT_MAIN2 LIKE TABLE OF GS_MAIN2.

SELECT *
  INTO CORRESPONDING FIELDS OF TABLE GT_DATA2
  FROM ZDSUWONT02.

SELECT *
  INTO CORRESPONDING FIELDS OF TABLE GT_DEPT2
  FROM ZDSUWONT02_3.

LOOP AT GT_DATA2 INTO GS_DATA2.
  CLEAR GS_DEPT2.
  READ TABLE GT_DEPT2 WITH KEY ZDEPT = GS_DATA2-ZDEPT INTO GS_DEPT2.
  IF SY-SUBRC = 0.
    GS_DATA2-ZDNAME = GS_DEPT2-ZDNAME.
    MODIFY GT_DATA2 FROM GS_DATA2.
    CLEAR GS_DATA2.
  ENDIF.
ENDLOOP.

SORT GT_DATA2.
LOOP AT GT_DATA2 INTO GS_DATA2.
  MOVE-CORRESPONDING GS_DATA2 TO GS_MAIN2.
  COLLECT GS_MAIN2 INTO GT_MAIN2.
ENDLOOP.

LOOP AT GT_MAIN2 INTO GS_MAIN2.
  WRITE : / GS_MAIN2-ZDEPT,
            GS_MAIN2-ZDNAME,
            GS_MAIN2-ZFAMNO.
ENDLOOP.
