*&---------------------------------------------------------------------*
*& Include          ZRSUWON02_TOP
*&---------------------------------------------------------------------*

TABLES : ZTSUWON02_HR.

DATA : BEGIN OF GT_DATA OCCURS 0,
        ICON(4),
        ZCODE TYPE ZTSUWON02_HR-ZCODE,
        ZNAME TYPE ZTSUWON02_HR-ZNAME,
        CHECK,
        INT TYPE I,
        NAME(100),
        OK_NO(2),

        INFO(4), "INFO_FNAME
        CTAB TYPE LVC_T_SCOL, "CTAB_FNAME
        STYLE TYPE LVC_T_STYL, "STYLEFNAME
       END OF GT_DATA.

DATA : OK_CODE TYPE SY-UCOMM.

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER.
DATA : GC_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
DATA : GC_CONTAINER_1 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_CONTAINER_2 TYPE REF TO CL_GUI_CONTAINER.
DATA : GC_GRID_1 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GC_GRID_2 TYPE REF TO CL_GUI_ALV_GRID.
DATA : GT_FCAT TYPE LVC_T_FCAT.
DATA : GS_FCAT TYPE LVC_S_FCAT.

DATA : GS_SORT TYPE LVC_S_SORT.
DATA : GT_SORT TYPE LVC_T_SORT.

DATA : LV_TABIX TYPE SY-TABIX.
DATA : GS_SCOL TYPE LVC_S_SCOL.
DATA : GS_STYLE TYPE LVC_S_STYL.

DATA : GS_VARIANT TYPE DISVARIANT.

DATA : GT_TOOLBAR TYPE UI_FUNCTIONS.

DATA : GS_LAYOUT TYPE LVC_S_LAYO.

DATA : GV_CHAR(10).

DATA : GC_EVENT TYPE REF TO EVENT. "이벤트 객체 선언?
