*&---------------------------------------------------------------------*
*& Report ZRSUWON02_06
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZRSUWON02_06.

TABLES : ZTSUWON02_HR.
*
*PARAMETERS : P_ZCODE TYPE ZTSUWON02_HR-ZCODE.
*
*WRITE : / P_ZCODE.
*
*PARAMETERS : P_1 TYPE C LENGTH 1 DEFAULT 'A',
*             P_2 TYPE CHAR1 DEFAULT 'B',
*             P_3 TYPE C DEFAULT 'C',
*             P_4(1) DEFAULT 'D',
*             P_5 DEFAULT 'E'.
*
*PARAMETERS : P_6 TYPE P DECIMALS 2 DEFAULT '123.45'.
*
*PARAMETERS : P_7 NO-DISPLAY.
*
*PARAMETERS : P_8 OBLIGATORY. "필수 값
*
*PARAMETERS : P_CHK AS CHECKBOX,
*             P_CHK2 AS CHECKBOX.
*
*PARAMETERS : RA_01 RADIOBUTTON GROUP GR1,
*             RA_02 RADIOBUTTON GROUP GR1. "둘 중 하나만 선택가능
*PARAMETERS : RA_04 RADIOBUTTON GROUP GR2,
*             RA_05 RADIOBUTTON GROUP GR2.
*
*SELECTION-SCREEN SKIP 3. "3라인을 엔터 치겠다
*
*SELECT-OPTIONS : S_ZCODE FOR ZTSUWON02_HR-ZCODE. "TABLES로 지정을 미리 해줘야 함.
*SELECT-OPTIONS : S_ZCODE2 FOR ZTSUWON02_HR-ZCODE NO-DISPLAY.
*SELECT-OPTIONS : S_ZCODE3 FOR ZTSUWON02_HR-ZCODE OBLIGATORY.
*
*SELECT-OPTIONS : S_ZCODE4 FOR ZTSUWON02_HR-ZCODE NO-EXTENSION.
*SELECT-OPTIONS : S_ZCODE5 FOR ZTSUWON02_HR-ZCODE NO INTERVALS.
*SELECT-OPTIONS : S_ZCODE6 FOR ZTSUWON02_HR-ZCODE
*                 NO-EXTENSION NO INTERVALS.
"SELECTION SCREEN OF
PARAMETERS : P_CHK1 AS CHECKBOX,
             P_CHK2 AS CHECKBOX,
             P_CHK3 AS CHECKBOX.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 1.
  SELECTION-SCREEN COMMENT (10) TEXT-S04.

  SELECTION-SCREEN POSITION 20.
  PARAMETERS : P_CHK4 AS CHECKBOX DEFAULT 'X'.
  SELECTION-SCREEN COMMENT (10) TEXT-S01 FOR FIELD P_CHK4.

  SELECTION-SCREEN POSITION 32.
  PARAMETERS : P_CHK5 AS CHECKBOX.
  SELECTION-SCREEN COMMENT (10) TEXT-S02 FOR FIELD P_CHK5.

  SELECTION-SCREEN POSITION 44.
  PARAMETERS : P_CHK6 AS CHECKBOX.
  SELECTION-SCREEN COMMENT (10) TEXT-S03 FOR FIELD P_CHK6.
SELECTION-SCREEN END OF LINE.

"RADIOBUTTON
SELECTION-SCREEN SKIP 4.

PARAMETERS : RA_03 RADIOBUTTON GROUP GR3,
             RA_04 RADIOBUTTON GROUP GR3.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN POSITION 1.
  SELECTION-SCREEN COMMENT (10) TEXT-S05.

  SELECTION-SCREEN POSITION 15.
  PARAMETERS : RA_05 RADIOBUTTON GROUP GR4.
  SELECTION-SCREEN COMMENT (10) TEXT-S06 FOR FIELD RA_05.

  SELECTION-SCREEN POSITION 28.
  PARAMETERS : RA_06 RADIOBUTTON GROUP GR4.
  SELECTION-SCREEN COMMENT (10) TEXT-S07 FOR FIELD RA_06.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME TITLE TEXT-B01.
  PARAMETERS : P_ZCODE1 TYPE ZTSUWON02_HR-ZCODE.
  SELECT-OPTIONS : S_ZCODE FOR ZTSUWON02_HR-ZCODE.
SELECTION-SCREEN END OF BLOCK BLOCK1.
